### ISSUE TITLE
Use Django psql full-text search instead of our own half-assed solution

### ISSUE THREAD

**Issue by Elarnon** [mangaki/mangaki#216]
https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/search/

**Comment by RaitoBezarius** [comment]
First, what do we want exactly?

- Trigrams?
- Full text search?
- Trigrams and full text search?

**Comment by jilljenn** [comment]
Voire ElasticSearch, cf. last CA.

**Comment by RaitoBezarius** [comment]
I tried to play around with the new Django lookups / co.

Actually, it won't be feasible to achieve the same performance with plain Django lookups:

- Now, Django have a `unaccent` lookup but it does not use our trick to make `unaccent` immutable, so we cannot put an index on it.
- Django has no `upper` lookup, we have to keep our `SearchSimilarity` at least (because `TrigramSimilarity` is really `SearchSimilarity` without UNACCENT/UPPER applied to lhs / rhs.)
- All we could use is the new `search` lookup or a `__unaccent__icontains` (w/o index though) lookup.

Let's move on ElasticSearch directly, I think, @Elarnon ?

**Comment by Elarnon** [comment]
Yes, agreed -- there are paths to make it feasible to handle this using PostgreSQL only (namely, using actual columns for search instead of expression indexes, which would also allow us to do some cool things more easily -- e.g. for multi-language support or typo correction), but it's probably not worth it as long as the plan is to switch to ES.
