### ISSUE TITLE
Modification manuelle des contenus : Langues des titres alternatifs

### ISSUE THREAD

**Issue by SubaruSumeragi** [mangaki/mangaki#318]
La liste des langues disponibles pour les titres alternatifs est vide rendant ainsi impossible toute modification manuelle d'une oeuvre dans le backoffice.
Cela ne bloque pas la fusion des oeuvres.

![2017-05-17_114933](https://cloud.githubusercontent.com/assets/4798290/26148580/735d7210-3af7-11e7-9ef0-fb048e6062a7.png)

**Comment by RaitoBezarius** [comment]
AFAIK, it seems related to the fact that no languages are available from the start.

@Elarnon We should seed Mangaki with a set of predefined languages, right?

**Comment by Elarnon** [comment]
Yes, we should make a data migration for that.

**Comment by RaitoBezarius** [comment]
I'd argue this is the job for a fixture, rather than a real data migration (i.e. empty migration + `RunPython`) ?

**Comment by Elarnon** [comment]
I think that a data migration (i.e. a `RunPython` migration) is more appropriate because this is data that we want automatically loaded into all Mangaki instances, and data that can change. If we use a fixture, it will be harder to keep the database in the proper state if/when we add/remove languages down the line, while migrations will handle that nicely (just make another migration that adds/remove languages as needed).
