### ISSUE TITLE
Reference objects should also be displayed inline in Work objects

### ISSUE THREAD

**Issue by jilljenn** [mangaki/mangaki#417]
Like WorkTitle, etc.

**Comment by SubaruSumeragi** [comment]
Tu peux préciser la demande ?

**Comment by RaitoBezarius** [comment]
@SubaruSumeragi If you take a look at the current admin page of a work, you'll see Reference objects are not displayed in an "inline" mode (i.e. their contents is not directly shown), whereas if you take a look to WorkTitle, you can take a look to immediately know which alternative titles are available on a work (i.e. their contents is shown directly on the page).

The desired behavior is to be able to look at a work's references directly rather than looking up reference one by one on their own page.
